name: Check Reported Proxies

on:
  schedule:
    - cron: '15 * * * *' # Runs automatically every hour. Change to '*/30 * * * *' for every 30 mins
  workflow_dispatch: # Allows you to click a button to run it manually

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests PySocks

      - name: Run Proxy Checker Script
        run: python proxy_report_checker.py
